// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfZ1pVt0iDJaAf7z-Dpe7dPZ_6R2p6Lc',
    appId: '1:819047256881:web:aab81ec79b292c87141610',
    messagingSenderId: '819047256881',
    projectId: 'fir-apptravel',
    authDomain: 'fir-apptravel.firebaseapp.com',
    storageBucket: 'fir-apptravel.appspot.com',
    measurementId: 'G-EDPK4DRJNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DPmDj_AvwKTnfADZUYrd3s0g5sHEDUg',
    appId: '1:819047256881:android:cedc49c700310a7f141610',
    messagingSenderId: '819047256881',
    projectId: 'fir-apptravel',
    storageBucket: 'fir-apptravel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOJFpD1vKIeZKE9W6cZvAYXJPYTtbjsE',
    appId: '1:819047256881:ios:67fdbd9fb4bf7f4d141610',
    messagingSenderId: '819047256881',
    projectId: 'fir-apptravel',
    storageBucket: 'fir-apptravel.appspot.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOJFpD1vKIeZKE9W6cZvAYXJPYTtbjsE',
    appId: '1:819047256881:ios:67fdbd9fb4bf7f4d141610',
    messagingSenderId: '819047256881',
    projectId: 'fir-apptravel',
    storageBucket: 'fir-apptravel.appspot.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbfZ1pVt0iDJaAf7z-Dpe7dPZ_6R2p6Lc',
    appId: '1:819047256881:web:d641c4a8b7c76346141610',
    messagingSenderId: '819047256881',
    projectId: 'fir-apptravel',
    authDomain: 'fir-apptravel.firebaseapp.com',
    storageBucket: 'fir-apptravel.appspot.com',
    measurementId: 'G-X7YC3XF4X1',
  );
}
