// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTym3shyhe9AG5GUISZEIfU9H7ajOog0Y',
    appId: '1:80335677485:android:95b2a38958712d1943f0a4',
    messagingSenderId: '80335677485',
    projectId: 'appgemini-c16ea',
    databaseURL: 'https://appgemini-c16ea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appgemini-c16ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfibpocYLBH3MLuV-eX5c7shNKCupkms',
    appId: '1:80335677485:ios:292dd39aad0dbebb43f0a4',
    messagingSenderId: '80335677485',
    projectId: 'appgemini-c16ea',
    databaseURL: 'https://appgemini-c16ea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appgemini-c16ea.appspot.com',
    iosClientId: '80335677485-0l5nr98peaq0t7hek3t3bchpjdhsus0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiAi',
  );
}
