name: shop_nike
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  cloud_firestore: ^5.2.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.2
  firebase_auth: ^5.2.0
  animations: ^2.0.11
  vertical_card_pager: ^1.6.2
  loading_animation_widget: ^1.3.0
  animated_text_kit: ^4.2.2
  typewritertext: ^3.0.9
  shimmer: ^3.0.0
  u_credit_card: ^1.4.0
  # flutter_native_splash: ^2.4.2
  flutter_stripe: ^11.2.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#   flutter_launcher_icons: ^0.14.1

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/img/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/nike-swoosh-logo.png
    - assets/img/Nike-logo-png-white.png
    - assets/img/user-profile.png
    - assets/img/icon.png
    - assets/img/screen_splast.png

  fonts:
    - family: ethnocentric
      fonts:
        - asset: assets/fonts/ethnocentric rg.otf
          weight: 700
    - family: Designer
      fonts:
        - asset: assets/fonts/Designer.otf
          weight: 700
    - family: CollegiateFLF
      fonts:
        - asset: assets/fonts/CollegiateFLF.ttf
          weight: 700
